# Site settings
title: "Bruno Volpato's Resume"
description: "A Brief History of Bruno's Time."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_theme: default
resume_avatar: "true"
resume_name: "Bruno Volpato"
resume_title: "Staff Software Engineer"
resume_contact_email: "me@brunovolpato.com"
resume_contact_telephone: "646-988-1413"
resume_contact_address: "New York, NY"
resume_header_contact_info: "New York, NY • 646-988-1413 • me@brunovolpato.com"
display_header_contact_info: "false"

resume_header_intro: "<p>Results-driven software engineer with over 15 years of professional experience in designing and implementing high-performance distributed systems and data platforms. Proven leadership in building and guiding technical teams to deliver scalable, robust solutions for complex systems.</p>"
resume_header_bottom: "<p><b>Specialties</b>:	Backend Engineering, Distributed Processing, Technical Leadership, Database Systems & Query Optimization, System/Data Platform Design, Search Engines, Messaging Protocols, Cloud Computing (Kubernetes/Docker), Application Profiling & Performance Tuning, Site Reliability Engineering</p>"
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
resume_section_interests: false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/bvolpato"
  resume_twitter_url: "http://x.com/bruflow"
  resume_linkedin_url: "https://www.linkedin.com/in/bvolpato"
  resume_website_url: "https://brunovolpato.com"
resume_print_social_links: true
